/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PAL_H_RPCGEN
#define _PAL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Input {
	char str[40];
};
typedef struct Input Input;

struct Output {
	char out[40];
};
typedef struct Output Output;

#define STR_PROG 0x23451111
#define STR_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define doopreation 1
extern  struct Output * doopreation_1(struct Input *, CLIENT *);
extern  struct Output * doopreation_1_svc(struct Input *, struct svc_req *);
extern int str_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define doopreation 1
extern  struct Output * doopreation_1();
extern  struct Output * doopreation_1_svc();
extern int str_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Input (XDR *, Input*);
extern  bool_t xdr_Output (XDR *, Output*);

#else /* K&R C */
extern bool_t xdr_Input ();
extern bool_t xdr_Output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PAL_H_RPCGEN */
