/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pal.h"

struct Output *
doopreation_1_svc(struct Input *argp, struct svc_req *rqstp)
{
	static struct Output  result;

	/*
	 * insert server code here
	 */

	return &result;
}
